### ISSUE TITLE
python tests are broken since the update of the v2 tag

### ISSUE THREAD

**Issue by glehmann** [tree-sitter/parser-test-action#3]
My python tests are broken since the update of the v2 apparently. The tests broke without any changes on my side — see the scheduled `ci` workflows in https://github.com/glehmann/tree-sitter-earthfile/actions

I’ve tried moving my test to `bindings/python/tests`, because this directory appear in the last commit in the current v2 tag and this dir is the error messages `ImportError: Start directory is not importable: 'bindings/python/tests'` but then the tests are failing because no test can be found.

Is there something else I should do?

**Comment by ObserverOfTime** [comment]
The test files must be named `test_*.py` for [test discovery] to find them.

[test discovery]: https://docs.python.org/3.12/library/unittest.html#test-discovery

**Comment by glehmann** [comment]
ok, nice to have moved to the standard convention 👍 
that plus removing the name parameter when creating the `Language` and my tests are green again :-)

<img width="410" alt="language" src="https://github.com/tree-sitter/parser-test-action/assets/325401/c5001692-4906-4915-a5e4-19118b55356f">
